### ISSUE TITLE
error - maybe just because no input provided

### ISSUE THREAD

**Issue by amelie-stein** [KULL-Centre/PRISM#19]
(base) [amelie@fend04 ddg_benchmark]$ run_ddG_pipeline_dev_amelie 
/lustre/hpc/sbinlab/amelie/projects/PRISM/ddg_benchmark
Traceback (most recent call last):
  File "/groups/sbinlab/amelie/projects/PRISM/PRISM/software/rosetta_ddG_pipeline/run_pipeline.py", line 148, in <module>
    predict_stability(sys.argv[1:])
  File "/groups/sbinlab/amelie/projects/PRISM/PRISM/software/rosetta_ddG_pipeline/run_pipeline.py", line 71, in predict_stability
    name = structure_list.split('/')[-1].split('.')[0] 
UnboundLocalError: local variable 'structure_list' referenced before assignment

**Comment by j0kaso** [comment]
which branch are you working on?

**Comment by amelie-stein** [comment]
main branch

**Comment by amelie-stein** [comment]
another error, now on dev branch:
Traceback (most recent call last):
  File "/groups/sbinlab/amelie/projects/PRISM/PRISM/software/rosetta_ddG_pipeline/run_pipeline.py", line 279, in <module>
    predict_stability(args)
  File "/groups/sbinlab/amelie/projects/PRISM/PRISM/software/rosetta_ddG_pipeline/run_pipeline.py", line 68, in predict_stability
    input_dict = storeinputs.storeinputfuc(name, args, folder)
  File "/lustre/hpc/sbinlab/amelie/projects/PRISM/PRISM/software/rosetta_ddG_pipeline/storeinputs.py", line 38, in storeinputfuc
    folder.input, basename(args.RELAX_FLAG_FILE)))
  File "/groups/sbinlab/haagenb/anaconda3/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/groups/sbinlab/amelie/projects/PRISM/PRISM/software/rosetta_ddG_pipeline/#/rosetta_parameters/relax_flagfile'

**Comment by j0kaso** [comment]
how did you call the program? did you provide a _relax_flagfile_?
did you adapt the paths in your bashrc?

```   'muscle_exec': '/groups/sbinlab/software/muscle/muscle3.8.31_i86linux64',
     'TMalign_exec': '/groups/sbinlab/software/TMalign/TMalign',
    'ddG_pipeline': '/sbinlab/software/PRISM/software/rosetta_ddG_pipeline',
    'Rosetta_main_path': '/sbinlab/software/Rosetta_2018_Oct_d557f8/source/',
    'Rosetta_tools_path': '/sbinlab/software/Rosetta_tools/tools/',
    'Rosetta_database_path': '/sbinlab/software/Rosetta_2018_Oct_d557f8/database/',
    'Rosetta_extension': 'linuxgccrelease',
    'prims_parser': '/sbinlab/tiemann/repos/PRISM/prism/scripts',
